services:
  iot_data_simulator_service:
    build:
      context: .
      dockerfile: ./iot_data_simulator/Dockerfile
    restart: on-failure
    ports:
      - "8081:80"
    environment:
      - CLIENT_COUNT=666
      - FREQUENCY=777
    develop:
      watch:
        - action: sync+restart
          path: ./iot_data_simulator
          target: itmo-mops-2024/iot_data_simulator

  iot_controller_service:
    build:
      context: .
      dockerfile: ./iot_controller/Dockerfile
    restart: on-failure
    ports:
      - "8082:5000"
    develop:
      watch:
        - action: sync
          path: ./iot_controller
          target: itmo-mops-2024/iot_controller

