services:
  datasim_service:
    build:
      context: ./datasim
    restart: on-failure
    ports:
      - "8081:80"
    #environment:
    #  - CLIENT_COUNT=666
    #  - FREQUENCY=777
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .

  controller_service:
    build:
      context: ./controller
    restart: on-failure
    ports:
      - "8082:5000"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .