services:
  controller:
    build:
      context: ./controller
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - controller_src:/controller/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .

  datasim:
    build:
      context: ./datasim
    restart: always
    volumes:
      - datasim_src:/datasim/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov

volumes:
  mongo_data:
  rabbitmq_data:
  controller_src:
  datasim_src: