services:
  datasim_service:
    build:
      context: ./datasim 
      #dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8081:80"
    #environment:
    #  - CLIENT_COUNT=666
    #  - FREQUENCY=777
    # volumes:
    #   -./datasim:./datasim
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .

