services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    depends_on:
      - rabbitmq

  controller:
    build:
      context: ./controller
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - controller_src:/controller/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - mongo

  rule_engine:
    build:
      context: ./rule_engine
    restart: always
    volumes:
      - rule_engine_src:/rule_engine/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - controller

  datasim:
    build:
      context: ./datasim
    restart: always
    volumes:
      - datasim_src:/datasim/src
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - rule_engine
  
volumes:
  mongo_data:
  rabbitmq_data:
  controller_src:
  datasim_src:
  rule_engine_src:

# networks:
#   backend:
#     driver: bridge
