global:
  scrape_interval: 5s
scrape_configs:
  - job_name: datasim
    static_configs:
      - targets:
          - datasim:8070
  - job_name: controller
    static_configs:
      - targets:
          - controller:8000
  - job_name: rule_engine
    static_configs:
      - targets:
          - rule_engine:8080
  - job_name: rabbitmq
    static_configs:
      - targets:
        - rabbitmq:15692