global:
  scrape_interval: 15s
scrape_configs:
  - job_name: datasim
    static_configs:
      - targets:
          - datasim:8070
  - job_name: controller
    static_configs:
      - targets:
          - controller:8000
  - job_name: rule_engine
    static_configs:
      - targets:
          - rule_engine:8080
